spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  webflux:
    base-path: /utdanning/ot
  kafka:
    consumer:
      group-id: consumer-utdanning-larling

fint:
  consumer:
    domain: utdanning
    package: ot
    org-id: ${fint.org-id}
  kafka:
    application-id: consumer-utdanning-ot
    enable-ssl: true
    topic:
      org-id: ${fint.org-id}
      domain-context: fint-core
  relations:
    default-base-url: https://beta.felleskomponent.no

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    org:
      springframework:
        security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus