spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  webflux:
    base-path: /utdanning/ot
  kafka:
    consumer:
      group-id: # consumer-utdanning-ot-<your-instance-id>

fint:
  security:
    open-paths: |
      /api-docs/**,
      /swagger/**,
      /actuator/prometheus
  consumer:
    domain: utdanning
    package: ot
    org-id: fintlabs.no
  kafka:
    application-id: consumer-utdanning-ot
    enable-ssl: true
    topic:
      org-id: fintlabs.no
      domain-context: fint-core
  relations:
    default-base-url: https://beta.felleskomponent.no

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    org:
      springframework:
        security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
