fint:
  security:
    open-paths: |
      /api-docs/**,
      /swagger/**
  kafka:
    application-id: consumer-utdanning-ot
    enable-ssl: false
    default-replicas: 1

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: consumer-utdanning-ot
  webflux:
    base-path: /utdanning/ot
  codec:
    max-in-memory-size: 200MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger/ui

logging:
  level:
    root: INFO