apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application.yaml
labels:
  - pairs:
      app.kubernetes.io/name: fint-core-consumer-utdanning-ot
      app.kubernetes.io/version: latest
      app.kubernetes.io/component: consumer
      app.kubernetes.io/part-of: fint-core
      fintlabs.no/team: core
