apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-consumer-utdanning-ot
spec:
  orgId: nfk.no
  url:
    hostname: api.felleskomponent.no
  kafka:
    enabled: true
    acls:
      - topic: 'nfk-no.fint-core.*'
        permission: admin
  resources:
    limits:
      memory: "1024Mi"
      cpu: "100m"
    requests:
      memory: "128Mi"
      cpu: "100m"